[server]
host = 192.168.1.100
port = 5000

[agent]
name = equipo-01
reconnect_interval = 30
send_interval = 5

[monitoring]
allowed_ports = 53,80,443,853,22
blacklist_domains = chatgpt.com,chat.openai.com,whatsapp.com,web.whatsapp.com,telegram.org,web.telegram.org,discord.com,discord.gg,reddit.com,facebook.com,instagram.com,twitter.com,x.com,tiktok.com,youtube.com,pastebin.com,github.com,stackoverflow.com,translate.google.com,deepl.com,gemini.google.com,copilot.microsoft.com,claude.ai
doh_ips = 1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4,9.9.9.9,149.112.112.112,208.67.222.222,208.67.220.220,94.140.14.14,94.140.15.15
